---
title: "Power Analysis for Future Hydration Studies"
author: "Savannah Weaver"
date: "Spring Quarter 2021"
output: pdf_document
---

# Packages

```{r setup, include=FALSE}
if (!require("tidyverse")) install.packages("tidyverse")
library("tidyverse")
if (!require("UsingR")) install.packages("UsingR")
library("UsingR")
if (!require("pwr")) install.packages("pwr")
library("pwr")
```



# Data

### Capture Data

```{r capture data}
capture_dat <- read.csv("./data/Herpetology_Data.csv",
                             na.strings=c("","NA") # fix empty cells
                             ) %>%
  dplyr::mutate(date = as.Date(date, format = "%m/%d/%y"),
                collect_time = as.POSIXct(collect_time, format = "%H:%M"),
                processing_time = as.POSIXct(processing_time, format = "%H:%M"),
                sex_M_F = as.factor(sex_M_F),
                gravid_Y_N = as.factor(gravid_Y_N),
                blood_sample_eye = as.factor(blood_sample_eye),
                hemolyzed = as.factor(hemolyzed.),
                #individual_ID = as.character(individual_ID),
                day = c(rep("0"))
                ) %>%
  dplyr::filter(osmolality_mmol_kg <= 500) %>% # remove one point I think inaccurate
  dplyr::select(date, individual_ID, 
                blood_sample_eye, 
                mass_g, 
                time = processing_time, 
                cloacal_temp_C, 
                hematocrit_percent,
                osmolality_mmol_kg,
                hemolyzed
                )
summary(capture_dat)
```


### Experiment Checkup Data

```{r exp data}
exp_dat <- read.csv("./data/experimental_data.csv",
                             na.strings=c("","NA") # fix empty cells
                             ) %>%
  dplyr::mutate(date = as.Date(date, format = "%m/%d/%y"),
                time = as.POSIXct(time, format = "%H:%M"),
                blood_sample_eye = as.factor(blood_sample_eye),
                hemolyzed = as.factor(hemolyzed),
                rehydration = as.factor(rehydration),
                #individual_ID = as.character(individual_ID)
                ) %>%
  dplyr::select(-notes, -rehydration) %>%
  dplyr::filter(osmolality_mmol_kg <= 500) # remove one point I think inaccurate
summary(exp_dat)
```



### Treatment Group Assignments

```{r}
tmt_groups <- read.csv("./data/exp_tmt_assignment.csv",
                             na.strings=c("","NA") # fix empty cells
                             ) %>%
  dplyr::filter(temp_tmt_C == 25) %>%
  dplyr::mutate(trial_number = as.factor(trial_number),
                humidity_tmt_percent = as.factor(humidity_tmt_percent),
                #individual_ID = as.character(individual_ID)
                ) %>%
  dplyr::select(-notes)
summary(tmt_groups)
```


### Join Data

```{r}
full_dat <- capture_dat %>%
  rbind(exp_dat) %>%
  left_join(tmt_groups, by = 'individual_ID')
summary(full_dat)
```


# Data Cleaning & Arrangement

```{r}
power_dat <- full_dat %>%
  group_by(individual_ID) %>%
  summarise(end_date = max(date),
            final_osmolality = osmolality_mmol_kg) %>%
  left_join(tmt_groups, by = 'individual_ID')
```




# Power Analyses





# Basic Figures
























